repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.7
  hooks:
  - id: clang-format
    args: [--style=Google]
    files: '\.(c|cc|cpp|h|hpp|cxx|hh)$'
- repo: https://github.com/pocc/pre-commit-hooks
  rev: master
  hooks:
    - id: cppcheck
